version: 1.0.{build}
build:
  verbosity: minimal
  project: bmc.sln

configuration: Release

environment:
  BOOST_ROOT: 'c:\Libraries\boost_1_59_0'
  QTDIR: 'C:\Qt\5.5\msvc2013'
  XSDDIR: 'C:\Program Files (x86)\CodeSynthesis XSD 4.0'

install:
  - git submodule --quiet update --init --recursive
  - curl.exe -s -o xsd-4.0.msi http://www.codesynthesis.com/download/xsd/4.0/windows/i686/xsd-4.0.msi
  - msiexec.exe /i xsd-4.0.msi /quiet /qn /norestart /log install.log

before_build:
  - cd %BOOST_ROOT%
  - bootstrap.bat --with-libraries=program_options
  - b2.exe --build-type=complete --with-program_options stage
  - cd c:\projects\bmc
  - set PATH=%QTDIR%\bin;%XSDDIR%\bin;%PATH%
  - set CMAKE_PREFIX_PATH=%QTDIR%;%CMAKE_PREFIX_PATH%
  - cmake -G "Visual Studio 14 2015" -Dbmc_USE_PYTHON=OFF -DXercesC_INCLUDE_DIR="%XSDDIR%\include" -DXercesC_LIBRARY_DEBUG="%XSDDIR%\lib\vc-12.0\xerces-c_3D.lib" -DXercesC_LIBRARY_RELEASE="%XSDDIR%\lib\vc-12.0\xerces-c_3.lib" .

build_script:
  - msbuild bmc.sln /t:bmc,bmc-ui,bmc_test /p:Configuration=Release
  - cd c:\projects\bmc\test
  - Release\bmc_test.exe

